version: "3"
services:
  rabbitmq:
    hostname: nowhere-rabbitmq
    image: rabbitmq:3-alpine
    restart: always
  mongodb:
    image: mvertes/alpine-mongo:latest
    restart: always
  mysql:
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DB}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASS}'
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always
    image: mysql/mysql-server:latest
  bind:
    image: ventz/bind
    restart: always
    volumes:
      - '../prod/etc/bind:/etc/bind'
  dns-vlan20-11:
    ports:
      - 65053:53/tcp
      - 65053:53/udp
    environment:
      - DNS_TTL=10
      - 'DNS_SUFFIX=${DNS_SUFFIX}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASS=${MYSQL_PASS}'
      - 'MYSQL_DB=${MYSQL_DB}'
      - USE_DOCKER_BIND=true
    restart: always
    build: ../../ruby-dns/
    links:
      - bind:bind1
      - bind:bind2
      - mysql:mysql
  xen-api:
    environment:
      - 'AMQP_URI=${AMQP_URI}'
      - 'XAPI_PATH=${XAPI_PATH}'
      - 'XAPI_PORT=${XAPI_PORT}'
      - 'XAPI_PASS=${XAPI_PASS}'
    restart: always
    build: ../../xen-api/
    links:
      - rabbitmq:nowhere-rabbitmq
  syslog-collector:
    ports:
      - 65514:514/tcp
      - 65514:514/udp
    environment:
      - 'MONGODB_URI=${MONGODB_URI}'
    links:
      - mongodb:nowhere-mongodb
    restart: always
    build: ../../node-mongo-syslog/
  api-gate:
    ports:
      - 3000:3000
    environment:
      - 'MONGODB_URI=${MONGODB_URI}'
      - 'AMQP_URI=${AMQP_URI}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASS=${MYSQL_PASS}'
      - 'MYSQL_DB=${MYSQL_DB}'
      - 'XAPI_PATH=${XAPI_PATH}'
      - 'XAPI_PORT=${XAPI_PORT}'
    links:
      - rabbitmq:nowhere-rabbitmq
      - mongodb:nowhere-mongodb
      - mysql:mysql
      - xen-api:xen-rest
    build: ../../node-api-gate/
